services:
  # Servicio 1: Contenedor de Entrenamiento
  trainer:
    build:
      context: .
      dockerfile: Dockerfile.train
    volumes:
      - ./data:/app/data        # Mapea los excels y CSV de feedback
      - ./models:/app/models    # Aquí se guardarán los .pkl
    container_name: vitis_trainer

  # Servicio 2: Contenedor de Inferencia (API)
  api:
    build:
      context: .
      dockerfile: Dockerfile.infer
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
      - ./data:/app/data        
    env_file:             
      - .env    
    depends_on:
      trainer:
        condition: service_completed_successfully
    container_name: vitis_api

  # Observabilidad
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    container_name: vitis_prometheus

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    depends_on:
      - prometheus

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    container_name: vitis_grafana
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  grafana_data: